version: 2
jobs:
  build:
    working_directory: ~/lunr-languages
    docker:
      - image: circleci/node:10.3.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: setuplibs
          command: LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
      - run:
          name: setuplibs2
          command: export LD_LIBRARY_PATH
      - run:
          name: test
          command: npm test
